### ISSUE TITLE
数据集0下载不了

### ISSUE THREAD

**Issue by LiquorPerfect** [ZhangMingliangAI/AiProducts-Challenge#4]
您好，wget https://tianchi-competition.oss-cn-hangzhou.aliyuncs.com/231780/AliProducts/002521585550641/train_val.part0.tar.gz这个数据集下载不了，请问一下有什么办法嘛。

**Comment by sandy-ssdut** [comment]
同问，请问有什么办法吗

**Comment by mingliangzhang2018** [comment]
可以问问官网或者官网所列参考文献的作者。

**Comment by xiaol827** [comment]
我感觉是链接给错了呢， @mingliangzhang2018 ，第0个数据

**Comment by mingliangzhang2018** [comment]
链接没有给错，但是数据集已经不能下载了，我这里也没有保存完整数据集。还有一部分样例，如果有需要可以邮件联系我。
